### ISSUE TITLE
Online rolling upgrade TiFlash

### ISSUE THREAD

**Issue by JaySon-Huang** [pingcap/tiflash#1437]
Users want their queries not to be greatly affected (meet unexpected errors) when upgrading TiFlash nodes

- [x] How to check all replicas are ready after users changed the replica number. Issue: #1436
- [x] TiDB-operator should wait for a TiFlash node to be upgraded is ready for providing service before upgrading the next TiFlash node. Issue: https://github.com/pingcap/tidb-operator/issues/3786, fix PR: https://github.com/pingcap/tidb-operator/pull/3789
- [x] #2525
- [ ] TiFlash should return "Region not found" for batch cop to let TiDB retry when TiFlash is terminating #1460
