### ISSUE TITLE
Identify and support push down for common functions

### ISSUE THREAD

**Issue by zanmato1984** [pingcap/tiflash#1847]
In sprint 4, we plan to support:
- [x] Mod MayPOC (https://github.com/pingcap/tics/issues/2318)
- [x] COALESCE MayPOC (https://github.com/pingcap/tics/issues/2334)
- [x] ASCII, length, position, trim (https://github.com/pingcap/tics/issues/2424)
- [x] ADDDATE, DATE, DATE_ADD (https://github.com/pingcap/tics/issues/2425)
- [x] ROUND() on Decimal (https://github.com/pingcap/tics/issues/2426)
- [x] INET_NTOA()/ATON(), INET6_ATON/NTOA() (https://github.com/pingcap/tics/issues/2427)
- [x] set、enum、INET_NTOA()、INET6_NTOA()、+/- INTERVAL X Y used quite a bit【Results Generation】
- [x] Math (https://github.com/pingcap/tics/issues/1901):  Ln  Log Log2 Log10 Exp Pow Radians Degrees Conv CRC32
- [x] Comparison (https://github.com/pingcap/tics/issues/1863): IsTrueWithNull, IsTrueWithoutNull, IsFalsity, NullEQ
- [ ] Bit op (https://github.com/pingcap/tics/issues/1900 and https://github.com/pingcap/tics/issues/1902): LeftShift, RightShift, LogicXor
- [x] Group concat distinct (https://github.com/pingcap/tics/issues/1908)

Sprint 3 done:
- [x] Replace (https://github.com/pingcap/tics/issues/1860)
- [x] Abs (https://github.com/pingcap/tics/issues/1937)
- [x] left/right (https://github.com/pingcap/tics/issues/1943)
- [x] str_to_date (https://github.com/pingcap/tics/issues/1942)
- [x] concat (https://github.com/pingcap/tics/issues/1940)
- [x] unix_timestamp (https://github.com/pingcap/tics/issues/1939)
- [x] cast string as double (https://github.com/pingcap/tics/issues/1936)
- [x] datediff, datesub, year, day, CastStringAsInt, CastTimeAsString, concat_ws, ifnull (https://github.com/pingcap/tics/issues/1480)
- [x] Math (https://github.com/pingcap/tics/issues/1901): Ceil, Ceiling, Floor, Sqrt

List by PM: https://docs.google.com/spreadsheets/d/1FUoFEhXXVFskkBLtTfGI0XqlgveW_IdFTOgvYD7PNcA/edit#gid=508440363
