### ISSUE TITLE
Interpreter & Executor & MPP unit test framework

### ISSUE THREAD

**Issue by ywqzzy** [pingcap/tiflash#4609]
## Enhancement
1. Since there is no unit test for the Interpreter module, Interpreter test framework aims to supplement the content of the unit test, improve the stability of the module, and find more hidden bugs at home.
2. TiFlash planner needs to rely on unit tests to ensure the quality and progress of development during the refactoring process.
3. User can mock input columns and feed them into the "Execution streams(BlockInputStreams in TiFlash)", then they can test executors(except MPP related logic) of TiFlash locally.
4. Further more, MPP related tests will be supported.
5. When developing more features in the future, good unit testing can be used as the basis for development to further improve the efficiency and quality of code development.

## Non MPP tests development progress:
- [x] #4610 
- [x] #4632 
- [x] #4706 
- [x] #4742 
- [x] #4788 
- [x] #4911 
- [x] #4858 
- [x] #5041 
- [x] #5021 
- [x] #5262 
- [x] #5295 
- [x] #5243 
- [x] #5347 
- [ ] #5345 
- [x] #5432 
- [ ] #5469 
- [x] #5510 
- [x] #5534 
- [x] #5419 
- [x] #5543
- [x] #5305  
- [x] #5889 add test log when failed.
- [x] #5957 
- [x] #5787
- [x] #5895 
- [x] #5915 
- [x] Test more types of executors[WIP].
- [ ] Support more expressions to test.
- [ ] More user friendly exception throw.
- [x] Check the legality and correctness of user input.
- [x] Add some easy to use template to write tests.
- [x] When result is wrong, print more user friendly message to help debug.
- [x] Add some built-in input columns for user to generate a bunch of tests.
- [x] Generate columns with different types and size. #5743 
- [ ] Generate columns following different data distribution.
- [x] Support regression test like this https://github.com/risinglightdb/sqlplannertest-rs. Here is the detail https://github.com/pingcap/tiflash/issues/6676
- [x] A document to demonstrate how to use the test framework.
- [ ] Bind test framework with google bench.
- [x] New executor should implement Serializer. New BlockInputStream should implement appendInfo().
- [ ] Improve the speed of tests.
- [ ] A test generator like sqlsmith.(Just for fun)
- [x] #6160 
- [x] #6561 
- [x] #7059 

## MPP tests development progress:
- [x] #5369 
- [x] #5450 
- [x] #5573
- [x] Orchestrate MPP Tasks.
- [x] Get task status of each TiFlash service. #5732 
- [x] Mock Storage.  #5573
- [x] #5732 
- [ ] Write TPCH queries in the framework!

## Run with storage layer
- [x] MockStorage with StorageDeltaMerge. #6561 
- [x] Support push down filter test #6573 

**Feel free to ask me anything about the Test Framework.**

**Comment by SeaRise** [comment]
Looks like the job is done
