### ISSUE TITLE
interpreter planner refactor

### ISSUE THREAD

**Issue by SeaRise** [pingcap/tiflash#4739]
#### background
Currently tiflash's interpreter is designed based on `DAGQueryBlock`.
`DAGQueryBlock` is designed to coprocess read, and it can handle simple queries well.
However, there is no way to handle the complex query of MPP, so the `DAGQueryBlock` tree is introduced, which is a compromise that makes the code more complicated and affects the subsequent iterative development.
We need to refactor the interpreter code in a plan visit way.

#### design
Therefore we introduce a new abstraction layer called `PhysicalPlan` to replace `DAGQueryBlock`.
It will be responsible for the processing of `ExpressionAction` and the generation of `BlockInputStream`.
We call this organization of code the planner.

```
DAGRequest (executor tree or executor array).
     |
     |
     v
physical plan <---+
     |            |
     |            | optimize
     |            |
     +------------+   
     |
     |
     v
BlockInputStream
```

#### why planner
Most databases are designed based on planner. 
- Friendly for database developers to understand code.
- We can improve tiflash with a general approach from the DB area, such as pipeline mode.

#### todo list
- [x] public desgin doc
    - #4743
- [x] Small refactoring of Interpreter before planner refactoring 
     - #4118 
- [x] interpreter test framework 
    - #4609 
- [x] planner refactory
    - [x] poc #4601 
    - [x] Introduce `PhysicalPlan`/`planner`, add switch and set it to planner by default
        - https://github.com/pingcap/tiflash/pull/4820 
    - [x] Replace all operators with `PhysicalPlan`
        - [x] common plans: projection/agg/filter/exchange_(sender/receiver)/limit/topn
            - https://github.com/pingcap/tiflash/pull/5143
        - [x] window function
            - https://github.com/pingcap/tiflash/pull/5363
        - [x] join
            - https://github.com/pingcap/tiflash/pull/5320
        - [x] table scan
            - https://github.com/pingcap/tiflash/pull/5335
    - [x] remove `DAGQueryBlock`
            - https://github.com/pingcap/tiflash/pull/5381
- [x] merge to master
    - feature branch: https://github.com/pingcap/tiflash/tree/planner_refactory
    - https://github.com/pingcap/tiflash/pull/5493
    - https://github.com/pingcap/tiflash/pull/5321

**Comment by SeaRise** [comment]
all merged.
