### ISSUE TITLE
Unified configuration management framework 

### ISSUE THREAD

**Issue by Lloyd-Pottiger** [pingcap/tiflash#5585]
## Feature Request

**Is your feature request related to a problem? Please describe:**

Now, the configuration is a mess. Some are configured by toml file, and some are recorded in the `dbms/src/Interpreters/Settings.h`. We initialize components by `global_context` and the default value has been decided in compiler time, even if the configuration has not been loaded, components can run smoothly.
There are cause some potential risks:
1. Some components initialize with default settings rather than the configuration in the input configuration file.
2. The configuration has changed during running, but we can not perceive it.

**Describe the feature you'd like:**

We need a unified configuration management framework in order to 
1. manage the configuration of different components together 
2. real-time awareness of the configuration. 
3. an interface to get the configuration for users

**Milestone**
- [ ] collect and classify all the configuration
- [ ] add a controller to manage configuration globally
- [ ] use the controller in all tiflash components
