### ISSUE TITLE
Support pipeline model

### ISSUE THREAD

**Issue by SeaRise** [pingcap/tiflash#6518]
## Enhancement
tiflash support pipeline model

#### todo list
- [x] public desgin doc
    - https://github.com/pingcap/tiflash/pull/7612 
- [x] pre-refactor
    - https://github.com/pingcap/tiflash/issues/5900 
- [ ] pipeline model
    - [x] support task scheduler and push model operator
        - [x] support task scheduler and simple operator(limit, projection, filter, mock(_scan/exchange_sender/receiver))
            - https://github.com/pingcap/tiflash/pull/6520 
        - [x] support complex operator
            - [x] aggregate
                - https://github.com/pingcap/tiflash/pull/6855
                - https://github.com/pingcap/tiflash/pull/7089
                - https://github.com/pingcap/tiflash/pull/7220
                - https://github.com/pingcap/tiflash/pull/7318
            - [x] join
              - https://github.com/pingcap/tiflash/pull/7333
              - https://github.com/pingcap/tiflash/pull/7833
            - [x] sort/window
              - https://github.com/pingcap/tiflash/pull/6963
              - https://github.com/pingcap/tiflash/pull/7492
            - [x] topn
              - https://github.com/pingcap/tiflash/pull/6805
              - https://github.com/pingcap/tiflash/pull/7216
         - [x] support fine grained shuffle
             - https://github.com/pingcap/tiflash/pull/6934
    - [x] support io executor
        - https://github.com/pingcap/tiflash/pull/7195
    - [x] support exchange / scan async io
        - [x] async table scan
          - https://github.com/pingcap/tiflash/pull/6831 
          - https://github.com/pingcap/tiflash/pull/7225
          - https://github.com/pingcap/tiflash/pull/7474
          - https://github.com/pingcap/tiflash/pull/7480
          - https://github.com/pingcap/tiflash/pull/7552
          - https://github.com/pingcap/tiflash/pull/7723
        - [x] async exchange sender/receiver
          - https://github.com/pingcap/tiflash/pull/6835
          - https://github.com/pingcap/tiflash/pull/6854
    - [ ] task schedule
        - [x] Multi-level feedback queue
            - https://github.com/pingcap/tiflash/pull/7393
        - [x] io_priority_queue
            - https://github.com/pingcap/tiflash/pull/7722
        - [ ] resource group
            - https://github.com/pingcap/tiflash/issues/7660
    - [x] other
        - [x] support explain analyze/mpp tracing
            - https://github.com/pingcap/tiflash/pull/6995
            - https://github.com/pingcap/tiflash/pull/7562
        - [x] improve log
            - https://github.com/pingcap/tiflash/pull/6921
        - [x] improve metrics
            - https://github.com/pingcap/tiflash/pull/7117
            - https://github.com/pingcap/tiflash/pull/7584
        - [x] failpoint
            - https://github.com/pingcap/tiflash/pull/6923 
        - [x] refine assert
            - https://github.com/pingcap/tiflash/pull/7343

**Comment by SeaRise** [comment]
Only resource control is left, which is tracked in other issues
