### ISSUE TITLE
Refactor DDL Module

### ISSUE THREAD

**Issue by hongyunyan** [pingcap/tiflash#7630]
## Enhancement
Our DDL module is too complex and inefficient, it can't work well under a large number tables with multiple ddl. In order to upport for a larger number of tables, we need to refactor ddl module.

For the new DDL infrastructure, we will do the following settings:
- [x] Make each table deal with its own inner schema changes( such as add columns, drop columns, modify columns, ..,etc), to avoid that multiple tables affect each other's performance due to schema changes
- [x] Only the schema changes between tables( such as create table, truncate table .. etc) will still sync in the background thread.
- [x] For the table without tiflash replica or table with no data, we will not create a physical table in tiflash, to reduce unnecessary space occupation.
- [x] For each keyspace, we use an independent schemaSyncer to update the schema synchronization to support the scalability under a large number of keyspaces.
- [x] Optimize DDLGuard(https://github.com/pingcap/tiflash/issues/7636)
- [x] Enhance TiFlashMetrics containing keyspace info(https://github.com/pingcap/tiflash/issues/7640)
- [ ] Don't store table schema locally by using schema.sql(https://github.com/pingcap/tiflash/issues/7311)
- [x] Parallel sync schema to speed up(https://github.com/pingcap/tiflash/issues/7641)

**Comment by JaySon-Huang** [comment]
We're going to close this issue because most of the reaction is done. The leftover issue remains as an enhancement for further investigation.
