### ISSUE TITLE
Fast add peer (FAP) issue tracker

### ISSUE THREAD

**Issue by CalvinNeo** [pingcap/tiflash#8673]
### Develop
- [ ] Shared write batch in `dropFAPTemp`.
- [x] Update schema in `FastAddPeerImplWrite` when doesn't find storage.
- [x] https://github.com/pingcap/tiflash/issues/7502

### Compatibility
1.
